// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheImageComparer.Logic.Data;

#nullable disable

namespace TheImageComparer.Logic.Migrations
{
    [DbContext(typeof(ImageComparerDbContext))]
    partial class ImageComparerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("TheImageComparer.Logic.Models.ImageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PossibleDuplicate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("TheImageComparer.Logic.Models.VoteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("VotedAgainstId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VotedForId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VotedAgainstId");

                    b.HasIndex("VotedForId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("TheImageComparer.Logic.Models.VoteModel", b =>
                {
                    b.HasOne("TheImageComparer.Logic.Models.ImageModel", "VotedAgainst")
                        .WithMany()
                        .HasForeignKey("VotedAgainstId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheImageComparer.Logic.Models.ImageModel", "VotedFor")
                        .WithMany()
                        .HasForeignKey("VotedForId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VotedAgainst");

                    b.Navigation("VotedFor");
                });
#pragma warning restore 612, 618
        }
    }
}
